### ISSUE TITLE
Figure out why all-pages-realtime.json isn't working

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/analytics.smgov.net#14]
Or is it? Maybe we just need to take this live and see it running in production?

**Comment by thekaveman** [comment]
I think our `threshold` value is probably too aggressive:

``` yaml
threshold:
  field: rt:activeUsers
  value: '10'
```

Let's take it down to 1
