### ISSUE TITLE
Backfill Socrata data

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/analytics.smgov.net#35]
Not so much an issue with our code, just a reminder todo.

Let's backfill the daily report data into Socrata, starting January 1, 2016.

**Comment by allejo** [comment]
Do the current GA IDs/properties have data dating back to Jan 1, 2016?

**Comment by thekaveman** [comment]
No, I guess not :weary:

I think we probably have data starting April 26, see 361d487

**Comment by allejo** [comment]
Google Analytics API supports the [`start-date` query to have a `YYYY-MM-DD` date](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#startDate) so we can use this to backfill. However... Around this time, the actual analytics filters were still being worked on so there are well over 10,000 entries; this isn't an issue for GA since we can just split up the queries into smaller time periods but what I'd like to know is if you'd like to have all of that unfiltered data (e.g. Google Mini, www vs non-www results, etc.) pushed to Socrata or should we have some sort of filter in this, otherwise, unfiltered data.

Here's what the report would look like; it's exactly the same as the `all-pages` report except with an explicit date.

``` yaml
frequency: once
meta:
  description: Data regarding each and every page dating back to 2016-04-26
  name: Back Fill
name: back-fill
query:
  dimensions:
  - ga:date
  - ga:hostname
  - ga:pagePath
  - ga:pageTitle
  end-date: yesterday
  start-date: 2016-04-26
  metrics:
  - ga:sessions
  - ga:percentNewSessions
  - ga:pageviews
  - ga:uniquePageviews
  - ga:avgTimeOnPage
  - ga:avgPageLoadTime
  - ga:entrances
  - ga:bounces
  - ga:exits
```
